//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirWCF3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:60745/v2", ConfigurationName="ServiceReference1.PedidoMultiplo")]
    public interface PedidoMultiplo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:60745/v2/PedidoMultiplo/RealizarPedido", ReplyAction="http://localhost:60745/v2/PedidoMultiplo/RealizarPedidoResponse")]
        string RealizarPedido(string[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:60745/v2/PedidoMultiplo/RealizarPedido", ReplyAction="http://localhost:60745/v2/PedidoMultiplo/RealizarPedidoResponse")]
        System.Threading.Tasks.Task<string> RealizarPedidoAsync(string[] item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PedidoMultiploChannel : ConsumirWCF3.ServiceReference1.PedidoMultiplo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoMultiploClient : System.ServiceModel.ClientBase<ConsumirWCF3.ServiceReference1.PedidoMultiplo>, ConsumirWCF3.ServiceReference1.PedidoMultiplo {
        
        public PedidoMultiploClient() {
        }
        
        public PedidoMultiploClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoMultiploClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoMultiploClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoMultiploClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RealizarPedido(string[] item) {
            return base.Channel.RealizarPedido(item);
        }
        
        public System.Threading.Tasks.Task<string> RealizarPedidoAsync(string[] item) {
            return base.Channel.RealizarPedidoAsync(item);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:60745/v1", ConfigurationName="ServiceReference1.PedidoUnico")]
    public interface PedidoUnico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:60745/v1/PedidoUnico/RealizarPedido", ReplyAction="http://localhost:60745/v1/PedidoUnico/RealizarPedidoResponse")]
        string RealizarPedido(int idProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:60745/v1/PedidoUnico/RealizarPedido", ReplyAction="http://localhost:60745/v1/PedidoUnico/RealizarPedidoResponse")]
        System.Threading.Tasks.Task<string> RealizarPedidoAsync(int idProduto, int quantidade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PedidoUnicoChannel : ConsumirWCF3.ServiceReference1.PedidoUnico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoUnicoClient : System.ServiceModel.ClientBase<ConsumirWCF3.ServiceReference1.PedidoUnico>, ConsumirWCF3.ServiceReference1.PedidoUnico {
        
        public PedidoUnicoClient() {
        }
        
        public PedidoUnicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoUnicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoUnicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoUnicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RealizarPedido(int idProduto, int quantidade) {
            return base.Channel.RealizarPedido(idProduto, quantidade);
        }
        
        public System.Threading.Tasks.Task<string> RealizarPedidoAsync(int idProduto, int quantidade) {
            return base.Channel.RealizarPedidoAsync(idProduto, quantidade);
        }
    }
}
